check_posts_without_assets_job:
  cron: "every hour"
  class: "CronJobCheckPostsWithoutAssets"
  # queue: cron_jobs
  # status: 'disabled'

mark_posts_on_sale_job:
  cron: "every day at 12:10am"
  class: "CronJobMarkPostsOnSale"
  # queue: cron_jobs
  # status: 'disabled'

unmark_posts_on_sale_job:
  cron: "every day at 12am"
  class: "CronJobUnmarkPostsOnSale"
  # queue: cron_jobs
  # status: 'disabled'

reset_user_codes_job:
  cron: "every 30 minutes"
  class: "CronJobResetUserCodes"
  # queue: cron_jobs
  # status: 'disabled'

send_notification_to_buyers_job:
  cron: "every day at 2am"
  class: "CronJobSendNotificationToBuyers"
  # queue: cron_jobs
  # status: 'disabled'

calculate_users_rating_job:
  cron: "every day at 3am"
  class: "CronJobCalculateUsersRating"
  # queue: cron_jobs
  # status: 'disabled'

check_posts_to_be_shipped_job:
  cron: "every hour"
  class: "CronJobCheckPostsToBeShipped"
  # queue: cron_jobs
  # status: 'disabled'

send_money_to_sellers_job:
  cron: "every hour"
  class: "CronJobSendMoneyToSellers"
  # queue: cron_jobs
  # status: 'disabled'

stats_engine_run_daily_job:
  cron: "every 30 minutes"
  class: "CronJobStatsEngineRunDaily"
  # queue: cron_jobs
  # status: 'disabled'

# stats_engine_run_total_job:
#   cron: "every hour"
#   class: "CronJobStatsEngineRunTotal"
#   # queue: cron_jobs
#   # status: 'disabled'

stats_engine_run_users_job:
  cron: "every 30 minutes"
  class: "CronJobStatsEngineRunUsers"
  # queue: cron_jobs
  # status: 'disabled'

stats_engine_run_users_total_job:
  cron: "every hour"
  class: "CronJobStatsEngineRunUsersTotal"
  # queue: cron_jobs
  # status: 'disabled'